/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_yxcoding_ktmvp_nativejni_NativeUtil_Companion */

#ifndef _Included_net_yxcoding_ktmvp_nativejni_NativeUtil_Companion
#define _Included_net_yxcoding_ktmvp_nativejni_NativeUtil_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_yxcoding_ktmvp_nativejni_NativeUtil_Companion
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_yxcoding_ktmvp_nativejni_NativeUtil_00024Companion_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     net_yxcoding_ktmvp_nativejni_NativeUtil_Companion
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_yxcoding_ktmvp_nativejni_NativeUtil_00024Companion_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_yxcoding_ktmvp_nativejni_NativeUtil_Companion
 * Method:    contactStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_yxcoding_ktmvp_nativejni_NativeUtil_00024Companion_contactStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
